// <auto-generated />
// RdpSignTool.exe — Standalone RDP file signer for RDPWrapKit.
//
// Compiles to a console EXE that signs an RDP file using the RDPWrapKit
// self-signed certificate.  Bypasses PowerShell entirely, eliminating
// ~5 seconds of PS startup + -EncodedCommand script parsing + Add-Type overhead.
//
// Exit codes:
//   0  = Success
//   1  = Certificate not found (not installed or EnsureRDPSigningCert not run)
//   2  = RDP file not found or unreadable
//   3  = Missing required "full address" field in RDP file
//   4  = Signing failed (CryptSignMessage error)
//   5  = Internal error / exception
//   99 = Invalid arguments
//
// Build:
//   csc.exe /target:exe /reference:System.dll /reference:System.Security.dll /reference:System.Core.dll /out:RdpSignTool.exe RdpSignTool.cs
//
// =============================================================================
// DEBUGGING / MAINTENANCE NOTES
// =============================================================================
//
// 1. ALTERNATE FULL ADDRESS MUST BE OVERRIDDEN IN CANONICAL SIGN SCOPE
//    (Issue: signatures appeared valid in rdp1 but not rdp2)
//
//    The canonical signscope bytes MUST include alternate full address set to
//    the value of full address, even when the input RDP file does NOT contain
//    an alternate full address field.  This is done in Step 6 (see fieldMap
//    override just below).
//
//    Root cause: when the old PowerShell signer (commit 93e0dbc) was ported
//    to C# (commit d094bd2), the fieldMap override for alternate full address
//    was omitted.  Newly-created shortcuts (first-time signing) lack the
//    alternate full address field, so the C# code fell back to the default
//    value "" for type 's'.  The signature was computed with an empty value,
//    but the output file was written with alternate full address = full address.
//    mstsc.exe then computed canonical bytes from the output file — getting the
//    non-empty value — and signature verification failed.
//
//    Verification method (PowerShell + C# P/Invoke):
//      - System.Security.Cryptography.Pkcs.SignedCms content + cms blob
//      - Canonical bytes computed with/without the override
//      - rdp0002 verified OK only with NO_OVERRIDE (empty value)
//      - After fix: both rdp1 and rdp2 verify OK with OVERRIDE
//      - Cross-verify: rdp1 CMS fails with NO_OVERRIDE (as expected)
//      - Error code: STATUS_INVALID_SIGNATURE (0xC000A000, -1073700864)
//
// 2. WRITESHORTCUTSETTINGSTORDPFILE CHANGES FILE ENCODING/LINE ENDINGS
//    The installer's WriteShortcutSettingsToRdpFile runs a PowerShell script
//    that uses [IO.File]::ReadAllLines() then [IO.File]::WriteAllLines().
//    This converts the RDP file from UTF-16LE+BOM+\r\r\n to UTF-8+\r\n.
//    RdpSignTool.exe then reads the UTF-8 file and re-writes it as
//    UTF-16LE+BOM+\r\r\n.  Both encodings are handled, so this is safe —
//    the field values are pure ASCII, so no data is lost.
//
// 3. TESTING SIGNATURES (requires admin for cert private key access)
//    To verify a signature from PowerShell (non-admin for CPS):
//      Add-Type -AssemblyName System.Security
//      $ci = New-Object Security.Cryptography.Pkcs.ContentInfo($canonBytes)
//      $sc = New-Object Security.Cryptography.Pkcs.SignedCms($ci, $true)
//      $sc.Decode($cmsBlob)
//      $sc.CheckSignature($true)
//    NOTE: The cert private key is in LocalMachine\My and requires
//    elevated process to access for signing, but verification via
//    SignedCms.CheckSignature() works without elevation.
//
// 4. CMS BLOB STRUCTURE IN RDP FILES
//    The signature in the RDP file has this wrapping:
//      [0-7]     Header: 01 00 01 00 01 00 00 00 (8 bytes)
//      [8-11]    Length: little-endian uint32 = CMS blob size
//      [12-end]  CMS/PKCS#7 detached SignedData blob
//    Base64-encoded with two-space separators every 64 chars (on one line).
//    The CMS blob contains the embedded signing certificate.
//    A valid signature produces an RSA-2048 PKCS#1 v1.5 encrypted digest
//    that exactly matches the SHA-256 hash of the canonical signscope bytes.
//
// 5. CANONICAL SIGN SCOPE FORMAT
//    For each field in SIGNSCOPE constant:
//      <lowercase-key>:<type>:<value>\r\n
//    Then appended:
//      signscope:s:<SIGNSCOPE>\r\n
//      \0 (null terminator)
//    Encoded as UTF-16LE (no BOM).
// =============================================================================

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.RegularExpressions;

// ---- Assembly metadata (shown in Windows Explorer -> Properties -> Details) ---

[assembly: AssemblyTitle("RdpSignTool")]
[assembly: AssemblyDescription("RDP File Signing Utility for RDPWrapKit")]
[assembly: AssemblyCompany("RDPWrapKit")]
[assembly: AssemblyProduct("RDPWrapKit Installer")]
[assembly: AssemblyCopyright("Copyright © 2024-2026 RDPWrapKit Contributors")]
[assembly: AssemblyVersion("1.1.0.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("1.1.0")]

namespace RdpWrapKit
{
    internal static class RdpSignTool
    {
        // ---- Constants --------------------------------------------------------

        private const string CERT_SUBJECT = "CN=RDPWrapKit: Only trust if connecting to 127.0.0.2";

        // Microsoft's canonical list of all signable RDP fields in their expected order.
        // For each field that exists in the file body, include it in the signscope
        // at this canonical position. Fields not in this list (e.g. redirectlocation,
        // camerastoredirect) are never signed.
        private static readonly CanonicalFieldInfo[] CANONICAL_SIGNSCOPE = {
            new CanonicalFieldInfo("full address",               "Full Address"),
            new CanonicalFieldInfo("alternate full address",      "Alternate Full Address"),
            new CanonicalFieldInfo("use redirection server name", "Use Redirection Server Name"),
            new CanonicalFieldInfo("negotiate security layer",    "Negotiate Security Layer"),
            new CanonicalFieldInfo("enablecredsspsupport",        "EnableCredSspSupport"),
            new CanonicalFieldInfo("disableconnectionsharing",    "DisableConnectionSharing"),
            new CanonicalFieldInfo("autoreconnection enabled",    "AutoReconnection Enabled"),
            new CanonicalFieldInfo("gatewayhostname",             "GatewayHostname"),
            new CanonicalFieldInfo("gatewayusagemethod",          "GatewayUsageMethod"),
            new CanonicalFieldInfo("gatewayprofileusagemethod",   "GatewayProfileUsageMethod"),
            new CanonicalFieldInfo("gatewaycredentialssource",    "GatewayCredentialsSource"),
            new CanonicalFieldInfo("promptcredentialonce",        "PromptCredentialOnce"),
            new CanonicalFieldInfo("alternate shell",             "Alternate Shell"),
            new CanonicalFieldInfo("shell working directory",     "Shell Working Directory"),
            new CanonicalFieldInfo("remoteapplicationprogram",    "RemoteApplicationProgram"),
            new CanonicalFieldInfo("remoteapplicationmode",       "RemoteApplicationMode"),
            new CanonicalFieldInfo("remoteapplicationguid",       "RemoteApplicationGuid"),
            new CanonicalFieldInfo("remoteapplicationname",       "RemoteApplicationName"),
            new CanonicalFieldInfo("remoteapplicationcmdline",    "RemoteApplicationCmdLine"),
            new CanonicalFieldInfo("prompt for credentials",      "Prompt For Credentials"),
            new CanonicalFieldInfo("authentication level",        "Authentication Level"),
            new CanonicalFieldInfo("audiomode",                   "AudioMode"),
            new CanonicalFieldInfo("redirectdrives",              "RedirectDrives"),
            new CanonicalFieldInfo("redirectprinters",            "RedirectPrinters"),
            new CanonicalFieldInfo("redirectcomports",            "RedirectCOMPorts"),
            new CanonicalFieldInfo("redirectsmartcards",          "RedirectSmartCards"),
            new CanonicalFieldInfo("redirectposdevices",          "RedirectPOSDevices"),
            new CanonicalFieldInfo("redirectclipboard",           "RedirectClipboard"),
            new CanonicalFieldInfo("devicestoredirect",           "DevicesToRedirect"),
            new CanonicalFieldInfo("drivestoredirect",            "DrivesToRedirect"),
            new CanonicalFieldInfo("loadbalanceinfo",             "LoadBalanceInfo"),
            new CanonicalFieldInfo("rdgiskdcproxy",               "RDGIsKDCProxy"),
            new CanonicalFieldInfo("kdcproxyname",                "KDCProxyName"),
            new CanonicalFieldInfo("enablerdsaadauth",            "EnableRdsAadAuth"),
            new CanonicalFieldInfo("redirectwebauthn",            "RedirectWebAuthn"),
        };

        // ---- Field type map (lower-case key -> 's' = string, 'i' = integer) ---

        private static readonly Dictionary<string, char> FieldTypeMap;
        private static readonly HashSet<string> StripKeys;

        static RdpSignTool()
        {
            FieldTypeMap = new Dictionary<string, char>(StringComparer.OrdinalIgnoreCase);
            FieldTypeMap.Add("full address", 's');
            FieldTypeMap.Add("alternate full address", 's');
            FieldTypeMap.Add("use redirection server name", 'i');
            FieldTypeMap.Add("negotiate security layer", 'i');
            FieldTypeMap.Add("enablecredsspsupport", 'i');
            FieldTypeMap.Add("disableconnectionsharing", 'i');
            FieldTypeMap.Add("autoreconnection enabled", 'i');
            FieldTypeMap.Add("gatewayhostname", 's');
            FieldTypeMap.Add("gatewayusagemethod", 'i');
            FieldTypeMap.Add("gatewayprofileusagemethod", 'i');
            FieldTypeMap.Add("gatewaycredentialssource", 'i');
            FieldTypeMap.Add("promptcredentialonce", 'i');
            FieldTypeMap.Add("alternate shell", 's');
            FieldTypeMap.Add("shell working directory", 's');
            FieldTypeMap.Add("remoteapplicationprogram", 's');
            FieldTypeMap.Add("remoteapplicationmode", 'i');
            FieldTypeMap.Add("remoteapplicationguid", 's');
            FieldTypeMap.Add("remoteapplicationname", 's');
            FieldTypeMap.Add("remoteapplicationcmdline", 's');
            FieldTypeMap.Add("loadbalanceinfo", 's');
            FieldTypeMap.Add("prompt for credentials", 'i');
            FieldTypeMap.Add("authentication level", 'i');
            FieldTypeMap.Add("audiomode", 'i');
            FieldTypeMap.Add("redirectdrives", 'i');
            FieldTypeMap.Add("redirectprinters", 'i');
            FieldTypeMap.Add("redirectcomports", 'i');
            FieldTypeMap.Add("redirectsmartcards", 'i');
            FieldTypeMap.Add("redirectposdevices", 'i');
            FieldTypeMap.Add("redirectclipboard", 'i');
            FieldTypeMap.Add("drivestoredirect", 's');
            FieldTypeMap.Add("devicestoredirect", 's');
            FieldTypeMap.Add("rdgiskdcproxy", 'i');
            FieldTypeMap.Add("kdcproxyname", 's');
            FieldTypeMap.Add("enablerdsaadauth", 'i');
            FieldTypeMap.Add("redirectwebauthn", 'i');

            StripKeys = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            StripKeys.Add("alternate full address");
            StripKeys.Add("signscope");
            StripKeys.Add("signature");
        }

        // ---- Crypt32 P/Invoke (same as RdpCrypt.cs) --------------------------

        private const uint PKCS_7_ASN_ENCODING = 0x00010000u;
        private const uint X509_ASN_ENCODING   = 0x00000001u;
        private const uint MSG_ENCODING        = PKCS_7_ASN_ENCODING | X509_ASN_ENCODING;

        [StructLayout(LayoutKind.Sequential)]
        private struct CRYPT_OBJID_BLOB
        {
            public uint   cbData;
            public IntPtr pbData;
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct CRYPT_ALGORITHM_IDENTIFIER
        {
            [MarshalAs(UnmanagedType.LPStr)] public string pszObjId;
            public CRYPT_OBJID_BLOB Parameters;
        }

        [StructLayout(LayoutKind.Sequential)]
        private struct CRYPT_SIGN_MESSAGE_PARA
        {
            public uint                   cbSize;
            public uint                   dwMsgEncodingType;
            public IntPtr                 pSigningCert;
            public CRYPT_ALGORITHM_IDENTIFIER HashAlgorithm;
            public IntPtr                 pvHashAuxInfo;
            public uint                   cMsgCert;
            public IntPtr                 rgpMsgCert;
            public uint                   cMsgCrl;
            public IntPtr                 rgpMsgCrl;
            public uint                   cAuthAttr;
            public IntPtr                 rgAuthAttr;
            public uint                   cUnauthAttr;
            public IntPtr                 rgUnauthAttr;
            public uint                   dwFlags;
            public uint                   dwInnerContentType;
            public CRYPT_ALGORITHM_IDENTIFIER HashEncryptionAlgorithm;
            public IntPtr                 pvHashEncryptionAuxInfo;
        }

        [DllImport("crypt32.dll", SetLastError = true)]
        private static extern bool CryptSignMessage(
            ref CRYPT_SIGN_MESSAGE_PARA pSignPara,
            [MarshalAs(UnmanagedType.Bool)] bool fDetachedSignature,
            uint    cToBeSigned,
            IntPtr[] rgpbToBeSigned,
            uint[]   rgcbToBeSigned,
            byte[]   pbSignedBlob,
            ref uint pcbSignedBlob
        );

        // ---- Entry point -----------------------------------------------------

        private static int Main(string[] args)
        {
            Stopwatch sw = Stopwatch.StartNew();

            try
            {
                if (args.Length < 1 || string.IsNullOrWhiteSpace(args[0]))
                {
                    Console.Error.WriteLine("RdpSignTool: ERROR: Usage: RdpSignTool.exe <path-to-rdp-file>");
                    return 99;
                }

                string rdpPath = args[0].Trim('"');
                Verbose("RdpSignTool v1.0 starting");

                // ---- Step 1: Validate RDP file exists -------------------------
                Verbose("RdpPath = " + rdpPath);
                if (!File.Exists(rdpPath))
                {
                    Console.Error.WriteLine("RdpSignTool: ERROR: File not found: " + rdpPath);
                    return 2;
                }

                // ---- Step 2: Find the signing cert ----------------------------
                Verbose("Looking for signing certificate...");
                X509Certificate2 cert = FindSigningCert();
                if (cert == null)
                {
                    Console.Error.WriteLine("RdpSignTool: ERROR: Signing certificate not found. Run EnsureRDPSigningCert first.");
                    return 1;
                }
                string thumb8 = (cert.Thumbprint != null && cert.Thumbprint.Length >= 8)
                    ? cert.Thumbprint.Substring(0, 8) : "????";
                Verbose("Certificate found: " + cert.Subject + " (thumb=" + thumb8 + "...)");

                // ---- Step 3: Read and parse RDP file --------------------------
                Verbose("Reading RDP file...");
                byte[] inputBytes = File.ReadAllBytes(rdpPath);
                string rawText;

                // Detect UTF-16LE BOM
                if (inputBytes.Length >= 2 && inputBytes[0] == 0xFF && inputBytes[1] == 0xFE)
                {
                    rawText = Encoding.Unicode.GetString(inputBytes, 2, inputBytes.Length - 2);
                    Verbose("Detected UTF-16LE encoding (BOM present)");
                }
                else
                {
                    rawText = Encoding.UTF8.GetString(inputBytes);
                    Verbose("Detected UTF-8 encoding (no BOM)");
                }

                // Split into lines (handle \r\r\n, \r\n, \r, \n)
                string[] inputLines = rawText.Split(
                    new[] { "\r\r\n", "\r\n", "\r", "\n" },
                    StringSplitOptions.RemoveEmptyEntries);
                Verbose("Parsed " + inputLines.Length + " lines");

                // ---- Step 4: Build field map ----------------------------------
                var fieldMap = new Dictionary<string, FieldEntry>(StringComparer.OrdinalIgnoreCase);
                foreach (string line in inputLines)
                {
                    Match match = Regex.Match(line, @"^(.+?):(.):(.*?)$");
                    if (match.Success)
                    {
                        string key = match.Groups[1].Value.Trim().ToLowerInvariant();
                        FieldEntry entry;
                        entry.Name = match.Groups[1].Value.Trim();
                        entry.Type = match.Groups[2].Value[0];
                        entry.Value = match.Groups[3].Value;
                        fieldMap[key] = entry;
                    }
                }

                if (!fieldMap.ContainsKey("full address"))
                {
                    Console.Error.WriteLine("RdpSignTool: ERROR: Missing required 'full address' field in RDP file.");
                    return 3;
                }
                Verbose("Field map built with " + fieldMap.Count + " entries");

                // ---- Step 5: Build base lines (strip old signscope/signature) --
                var baseLines = new List<string>();
                foreach (string line in inputLines)
                {
                    string lineTrimmed = line.Trim();
                    if (string.IsNullOrEmpty(lineTrimmed))
                        continue;

                    Match binaryMatch = Regex.Match(lineTrimmed, @"^(.+?):b:(.*)$");
                    if (binaryMatch.Success)
                    {
                        string key = binaryMatch.Groups[1].Value.Trim().ToLowerInvariant();
                        if (!StripKeys.Contains(key))
                            baseLines.Add(binaryMatch.Groups[1].Value.Trim() + ":b:" + binaryMatch.Groups[2].Value.Trim().ToUpperInvariant());
                        // Binary fields (password 51:b) are NEVER in signscope
                    }
                    else
                    {
                        Match fieldMatch = Regex.Match(lineTrimmed, @"^(.+?):");
                        if (fieldMatch.Success)
                        {
                            string key = fieldMatch.Groups[1].Value.Trim().ToLowerInvariant();
                            if (!StripKeys.Contains(key))
                                baseLines.Add(lineTrimmed);
                        }
                        else
                        {
                            // Skip orphaned lines that look like bare base64 data
                            // (e.g. old signature continuation without 'signature:s:' prefix).
                            // These are artifacts from previous signings that used a different
                            // wrapping format.  Valid RDP fields always have a colon.
                            if (lineTrimmed.IndexOf(':') < 0)
                            {
                                // Pure base64 chars: A-Za-z0-9+/=
                                bool looksLikeBase64 = true;
                                for (int ci = 0; ci < lineTrimmed.Length; ci++)
                                {
                                    char c = lineTrimmed[ci];
                                    if (!((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') ||
                                          (c >= '0' && c <= '9') || c == '+' || c == '/' || c == '='))
                                    {
                                        looksLikeBase64 = false;
                                        break;
                                    }
                                }
                                if (!looksLikeBase64)
                                    baseLines.Add(lineTrimmed);
                                // else: skip — it's orphaned base64 signature data
                            }
                            else
                            {
                                baseLines.Add(lineTrimmed);
                            }
                        }
                    }
                }
                Verbose("Built " + baseLines.Count + " base lines (stripped old signature)");

                // ---- Step 6: Build canonical signscope ------------------------
                string altFullAddress = fieldMap["full address"].Value;

                // Override alternate full address in the field map so the canonical
                // signscope always includes the correct value, even when the input
                // file is missing this field (e.g. newly-created shortcuts that
                // have never been signed before).  This matches the legacy PS
                // implementation and avoids a mismatch where the output file
                // receives alternate full address = fullAddress but the signature
                // was computed with alternate full address = "".
                FieldEntry altEntry;
                altEntry.Name = "alternate full address";
                altEntry.Type = 's';
                altEntry.Value = altFullAddress;
                fieldMap["alternate full address"] = altEntry;

                // Build signscope from Microsoft's canonical field list.
                // Only include fields that actually exist in the file body.
                // This matches rdpsign.exe behavior exactly — same fields, same canonical order.
                var effectiveScopeFields = new List<string>();
                foreach (CanonicalFieldInfo cfi in CANONICAL_SIGNSCOPE)
                {
                    if (fieldMap.ContainsKey(cfi.Key))
                        effectiveScopeFields.Add(cfi.DisplayName);
                }
                string effectiveSignscope = string.Join(",", effectiveScopeFields);

                string[] scopeFields = effectiveSignscope.Split(',');

                StringBuilder sb = new StringBuilder();
                foreach (string sf in scopeFields)
                {
                    string key = sf.Trim().ToLowerInvariant();
                    string typ;
                    string val;

                    FieldEntry entry;
                    char mappedType;
                    if (fieldMap.TryGetValue(key, out entry))
                    {
                        typ = entry.Type.ToString();
                        val = entry.Value;
                    }
                    else if (FieldTypeMap.TryGetValue(key, out mappedType))
                    {
                        typ = mappedType.ToString();
                        val = (mappedType == 's') ? "" : "0";
                    }
                    else
                    {
                        // Unknown field - skip
                        continue;
                    }

                    sb.Append(key + ":" + typ + ":" + val + "\r\n");
                }
                sb.Append("signscope:s:" + effectiveSignscope + "\r\n");
                sb.Append('\0'); // null terminator

                byte[] canonicalBytes = Encoding.Unicode.GetBytes(sb.ToString());
                Verbose("Canonical signscope built (" + canonicalBytes.Length + " bytes)");

                // ---- Step 7: Sign via CryptSignMessage ------------------------
                Verbose("Calling CryptSignMessage...");
                byte[] cmsBytes = SignDetached(canonicalBytes, cert);
                Verbose("CMS signature produced (" + cmsBytes.Length + " bytes)");

                // ---- Step 8: Build output RDP content -------------------------
                byte[] header = { 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00 };
                byte[] sigBlob = Combine(header, BitConverter.GetBytes((uint)cmsBytes.Length), cmsBytes);
                string b64Raw = Convert.ToBase64String(sigBlob);

                // Wrap base64: insert two spaces after every 64 characters, keeping
                // the ENTIRE signature value on ONE RDP file line (matching rdpsign.exe
                // and the original PowerShell implementation exactly).
                // Regex equivalent: .Replace(b64Raw, '.{1,64}', '$0  ')
                StringBuilder b64Wrapped = new StringBuilder(b64Raw.Length + (b64Raw.Length / 64 + 1) * 2);
                for (int i = 0; i < b64Raw.Length; i += 64)
                {
                    int len = Math.Min(64, b64Raw.Length - i);
                    b64Wrapped.Append(b64Raw, i, len);
                    b64Wrapped.Append("  "); // two-space separator — stays on same line
                }
                string sigB64 = b64Wrapped.ToString().TrimEnd(' ');

                // Build output lines
                var outLines = new List<string>(baseLines);
                outLines.Add("alternate full address:s:" + altFullAddress);
                outLines.Add("signscope:s:" + effectiveSignscope);
                outLines.Add("signature:s:" + sigB64);

                string outText = string.Join("\r\r\n", outLines) + "\r\r\n";
                byte[] outBytes = Combine(
                    new byte[] { 0xFF, 0xFE },  // UTF-16LE BOM
                    Encoding.Unicode.GetBytes(outText));

                // ---- Step 9: Write signed RDP file ---------------------------
                Verbose("Writing signed RDP file (" + outBytes.Length + " bytes)...");
                File.WriteAllBytes(rdpPath, outBytes);

                Verbose("RdpSignTool completed successfully in " + sw.ElapsedMilliseconds + "ms");
                return 0;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("RdpSignTool: ERROR: " + ex.GetType().Name + ": " + ex.Message);
                if (ex.InnerException != null)
                    Console.Error.WriteLine("RdpSignTool: INNER: " + ex.InnerException.Message);
                Console.Error.WriteLine("RdpSignTool: STACK: " + ex.StackTrace);
                return 5;
            }
        }

        // ---- Helpers ---------------------------------------------------------

        private static X509Certificate2 FindSigningCert()
        {
            X509Store store = new X509Store(StoreName.My, StoreLocation.LocalMachine);
            try
            {
                store.Open(OpenFlags.OpenExistingOnly | OpenFlags.ReadOnly);
                foreach (X509Certificate2 cert in store.Certificates)
                {
                    if (string.Equals(cert.Subject, CERT_SUBJECT, StringComparison.OrdinalIgnoreCase))
                        return cert;
                }
            }
            finally
            {
                store.Close();
            }
            return null;
        }

        private static byte[] SignDetached(byte[] content, X509Certificate2 cert)
        {
            if (content == null) throw new ArgumentNullException("content");
            if (cert == null) throw new ArgumentNullException("cert");
            if (content.Length == 0) throw new ArgumentException("Content must not be empty.", "content");

            IntPtr certPtrArr = Marshal.AllocHGlobal(IntPtr.Size);
            try
            {
                Marshal.WriteIntPtr(certPtrArr, cert.Handle);

                CRYPT_SIGN_MESSAGE_PARA para = new CRYPT_SIGN_MESSAGE_PARA();
                para.cbSize = (uint)Marshal.SizeOf(typeof(CRYPT_SIGN_MESSAGE_PARA));
                para.dwMsgEncodingType = MSG_ENCODING;
                para.pSigningCert = cert.Handle;
                para.HashAlgorithm = new CRYPT_ALGORITHM_IDENTIFIER();
                para.HashAlgorithm.pszObjId = "2.16.840.1.101.3.4.2.1"; // SHA-256
                para.cMsgCert = 1u;
                para.rgpMsgCert = certPtrArr;

                GCHandle handle = GCHandle.Alloc(content, GCHandleType.Pinned);
                try
                {
                    IntPtr contentPtr = handle.AddrOfPinnedObject();
                    IntPtr[] rgpb = { contentPtr };
                    uint[] rgcb = { (uint)content.Length };

                    // Query size
                    uint cbBlob = 0;
                    if (!CryptSignMessage(ref para, true, 1u, rgpb, rgcb, null, ref cbBlob))
                    {
                        int err = Marshal.GetLastWin32Error();
                        throw new Win32Exception(err, "CryptSignMessage size query failed (error " + err + ")");
                    }

                    if (cbBlob == 0)
                        throw new Win32Exception(0, "CryptSignMessage returned zero-size output buffer.");

                    // Produce signature
                    byte[] blob = new byte[cbBlob];
                    if (!CryptSignMessage(ref para, true, 1u, rgpb, rgcb, blob, ref cbBlob))
                    {
                        int err = Marshal.GetLastWin32Error();
                        throw new Win32Exception(err, "CryptSignMessage failed (error " + err + ")");
                    }

                    if (cbBlob == blob.Length)
                        return blob;

                    byte[] trimmed = new byte[cbBlob];
                    Buffer.BlockCopy(blob, 0, trimmed, 0, (int)cbBlob);
                    return trimmed;
                }
                finally
                {
                    if (handle.IsAllocated)
                        handle.Free();
                }
            }
            finally
            {
                Marshal.FreeHGlobal(certPtrArr);
            }
        }

        private static byte[] Combine(params byte[][] arrays)
        {
            int total = 0;
            for (int i = 0; i < arrays.Length; i++)
                total += arrays[i].Length;

            byte[] result = new byte[total];
            int offset = 0;
            for (int i = 0; i < arrays.Length; i++)
            {
                Buffer.BlockCopy(arrays[i], 0, result, offset, arrays[i].Length);
                offset += arrays[i].Length;
            }
            return result;
        }

        [Conditional("DEBUG")]
        private static void Verbose(string message)
        {
            // Writes to stderr so they don't interfere with stdout (not used here)
            Console.Error.WriteLine("RdpSignTool: " + message);
        }

        private struct FieldEntry
        {
            public string Name;
            public char Type;
            public string Value;
        }

        private struct CanonicalFieldInfo
        {
            public string Key;
            public string DisplayName;
            public CanonicalFieldInfo(string key, string displayName)
            {
                Key = key;
                DisplayName = displayName;
            }
        }
    }
}
