plugins:
  - jekyll-readme-index
  - jekyll-remote-theme

readme_index:
  enabled: true
  remove_originals: false

theme: jekyll-theme-slate

title: RDPWrapKit
description: The all-in-one installer for local RDP setup

